### ISSUE TITLE
为什么加了你的键盘库 UITextField 代理方法不响应呢?

### ISSUE THREAD

**Issue by cweilouis** [ChandHsu/XQKeyboard#2]
为什么加了你的键盘库 UITextField 代理方法不响应呢?
为什么加了你的键盘库 UITextField 代理方法不响应呢?
为什么加了你的键盘库 UITextField 代理方法不响应呢?
求教???

**Comment by ChandHsu** [comment]
据我所知,只有系统键盘会调用全部的代理方法,也没有找到解决办法,目前你可以修改XQKeyboard内部代码实现自主监听.🙂

**Comment by ChandHsu** [comment]
粗略的实现了一下,现在可以正常使用了

**Comment by ChandHsu** [comment]
已修复!🙂

**Comment by ChandHsu** [comment]
已修复!🙂,原因是没有在赋值的时候调用代理方法授权
